---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f about.html $DEPLOYPATH
    - /bin/cp -f projects.html $DEPLOYPATH
    - /bin/cp -f donate.html $DEPLOYPATH
    - /bin/cp -Rf assets $DEPLOYPATH
